name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ "main" ]

env:
  JAVA_VERSION: '17'
  WORKING_DIR: feedback-system

  # Variáveis fake para testes
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: fake-access-key
  AWS_SECRET_ACCESS_KEY: fake-secret-key
  AWS_SNS_FEEDBACK_TOPIC_ARN: arn:aws:sns:us-east-1:123456789012:fake-topic
  AWS_SQS_FEEDBACK_URL: https://sqs.us-east-1.amazonaws.com/123456789012/fake-queue
  FEEDBACK_TABLE_NAME: FakeTable

jobs:
  build-and-analyze:
    name: Build, Test & SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necessário para SonarQube

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build, Test & Analyze
        working-directory: ${{ env.WORKING_DIR }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Airassilva_Fase-04

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ${{ env.WORKING_DIR }}/target/surefire-reports/
          retention-days: 7

      - name: Update dependency graph
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        with:
          directory: ${{ env.WORKING_DIR }}